# Generated by Django 4.0.5 on 2022-07-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0012_alter_entitymanagementmodel_entity_mpesa_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesa_transaction',
            name='user',
        ),
    ]
